### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jaredphillips** [leereilly/static-site-heroku-cedar-example#2]
In config.ru file add the following:
  :urls => ["/images", "/js", "css"],

Should be "/css". 

Otherwise, worked like a charm. Thank you.

**Comment by sagarjunnarkar** [comment]
Hi @jaredphillips,
    `config.ru` is updated on 22nd July 2012. See [this commit](https://github.com/leereilly/static-site-heroku-cedar-example/commit/c16f574238b0eafbe92e8d6b989659ba2b264df4).

Problem is in `README.md` I have opened a [pull request](https://github.com/sagarjunnarkar/static-site-heroku-cedar-example/commit/74c6fdf7db2f8a2a9afd6de5822ff0c9e68db2df).

**Comment by leereilly** [comment]
Thanks for reporting @jaredphillips and thanks for fixing @sagarjunnarkar :metal:
